// Class: ReadVBFgamma
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::VBFgamma
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.18/04       [397828]
Creator        : ntonon
Date           : Mon Sep  6 17:18:18 2021
Host           : Linux cmspcx36679 4.15.0-1079-oem #89-Ubuntu SMP Fri Mar 27 05:22:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/ntonon/Postdoc/VBFgamma/Analysis
Training events: 200000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "200" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e-01" [Learning rate for BoostType=Grad algorithm]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
vjj_newvarisotropy            vjj_newvarisotropy            vjj_newvarisotropy            vjj_newvarisotropy                                              'F'    [0.13966922462,0.998886108398]
vjj_newvarcircularity         vjj_newvarcircularity         vjj_newvarcircularity         vjj_newvarcircularity                                           'F'    [0.00174968014471,0.906690955162]
vjj_newvarsphericity          vjj_newvarsphericity          vjj_newvarsphericity          vjj_newvarsphericity                                            'F'    [0.000284228706732,0.922964036465]
vjj_newvaraplanarity          vjj_newvaraplanarity          vjj_newvaraplanarity          vjj_newvaraplanarity                                            'F'    [8.0503603729e-14,0.417866587639]
vjj_newvarC                   vjj_newvarC                   vjj_newvarC                   vjj_newvarC                                                     'F'    [0.000568367715459,0.991529047489]
vjj_newvarD                   vjj_newvarD                   vjj_newvarD                   vjj_newvarD                                                     'F'    [5.70928327943e-14,0.97432911396]
vjj_newvarjj_vdphi            vjj_newvarjj_vdphi            vjj_newvarjj_vdphi            vjj_newvarjj_vdphi                                              'F'    [0.00113439559937,6.28253984451]
vjj_newvarsublead_dphivj      vjj_newvarsublead_dphivj      vjj_newvarsublead_dphivj      vjj_newvarsublead_dphivj                                        'F'    [0,6.28306341171]
vjj_newvarlead_dphivj         vjj_newvarlead_dphivj         vjj_newvarlead_dphivj         vjj_newvarlead_dphivj                                           'F'    [0,6.28269720078]
vjj_newvarsublead_detavj      vjj_newvarsublead_detavj      vjj_newvarsublead_detavj      vjj_newvarsublead_detavj                                        'F'    [0,6.8818359375]
vjj_newvarlead_detavj         vjj_newvarlead_detavj         vjj_newvarlead_detavj         vjj_newvarlead_detavj                                           'F'    [0,6.4345703125]
vjj_newvarleadJet_qgl         vjj_newvarleadJet_qgl         vjj_newvarleadJet_qgl         vjj_newvarleadJet_qgl                                           'F'    [-1,1]
vjj_newvarvjj_deta            vjj_newvarvjj_deta            vjj_newvarvjj_deta            vjj_newvarvjj_deta                                              'F'    [0,8.65625]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new VBFgammaNode

#ifndef VBFgammaNode__def
#define VBFgammaNode__def

class VBFgammaNode {

public:

   // constructor of an essentially "empty" node floating in space
   VBFgammaNode ( VBFgammaNode* left,VBFgammaNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~VBFgammaNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   VBFgammaNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   VBFgammaNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   VBFgammaNode*   fLeft;     // pointer to the left daughter node
   VBFgammaNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   VBFgammaNode::~VBFgammaNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool VBFgammaNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool VBFgammaNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadVBFgamma : public IClassifierReader {

 public:

   // constructor
   ReadVBFgamma( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadVBFgamma" ),
        fNvars( 13 )
   {
      // the training input variables
      const char* inputVars[] = { "vjj_newvarisotropy", "vjj_newvarcircularity", "vjj_newvarsphericity", "vjj_newvaraplanarity", "vjj_newvarC", "vjj_newvarD", "vjj_newvarjj_vdphi", "vjj_newvarsublead_dphivj", "vjj_newvarlead_dphivj", "vjj_newvarsublead_detavj", "vjj_newvarlead_detavj", "vjj_newvarleadJet_qgl", "vjj_newvarvjj_deta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadVBFgamma() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<VBFgammaNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadVBFgamma::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      VBFgammaNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(VBFgammaNode*)current->GetRight();
         else current=(VBFgammaNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
}

void ReadVBFgamma::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266198,-0.0467603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473403,-0.00531934) , 
11, 0.741294, 1, 0, 0.344068,-0.155932) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459236,-0.00815277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725552,0.0451104) , 
10, 1.69884, 1, 0, 0.566557,0.0665571) , 
9, 1.09562, 1, 0, 0.5,5.66539e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62319,0.0237768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368141,-0.0250855) , 
4, 0.212565, 1, 0, 0.54414,0.0430991) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195357,-0.0593242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390022,-0.0219149) , 
11, 0.741294, 1, 0, 0.264879,-0.229571) , 
12, 2.84235, 1, 0, 0.5,1.10254e-06)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617228,0.0210962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357856,-0.0261689) , 
5, 0.00484741, 1, 0, 0.54414,0.0387904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195357,-0.0536988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390022,-0.019734) , 
11, 0.741294, 1, 0, 0.264879,-0.206656) , 
12, 2.84235, 1, 0, 0.5,-4.62848e-06)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266198,-0.0400515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473403,-0.00492676) , 
11, 0.741294, 1, 0, 0.344068,-0.133157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454537,-0.00748121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718506,0.0371338) , 
10, 1.63707, 1, 0, 0.566557,0.0568125) , 
9, 1.09562, 1, 0, 0.5,-1.64702e-05)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640638,0.0231005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418176,-0.0133845) , 
4, 0.118892, 1, 0, 0.535175,0.0286545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225116,-0.0454938) , 
12, 3.18688, 1, 0, 0.5,-1.10421e-05)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266198,-0.0360643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473403,-0.00438351) , 
11, 0.741294, 1, 0, 0.344068,-0.118637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465074,-0.00488134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.732265,0.0351913) , 
10, 1.76062, 1, 0, 0.566557,0.0506138) , 
9, 1.09562, 1, 0, 0.5,-1.71841e-05)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416129,-0.0161135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217647,-0.0482892) , 
4, 0.14469, 1, 0, 0.309418,-0.16434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305741,-0.0284018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585111,0.0136566) , 
9, 0.624813, 1, 0, 0.536653,0.0315948) , 
11, 0.0646766, 1, 0, 0.5,-9.36004e-06)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601735,0.0146441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357487,-0.0202177) , 
5, 0.00484741, 1, 0, 0.535175,0.0252374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225116,-0.0408697) , 
12, 3.18688, 1, 0, 0.5,-2.31183e-05)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43078,-0.0103883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667746,0.0237182) , 
10, 1.68079, 1, 0, 0.547765,0.0309955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.356044,-0.0156051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209586,-0.0434311) , 
3, 0.0012478, 1, 0, 0.285384,-0.139466) , 
12, 2.67009, 1, 0, 0.5,-3.59386e-05)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444171,0.00175654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295161,-0.0309168) , 
4, 0.0548, 1, 0, 0.344068,-0.0986623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60569,0.0141171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208678,-0.0423176) , 
12, 3.40221, 1, 0, 0.566557,0.0420608) , 
9, 1.09562, 1, 0, 0.5,-3.62112e-05)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645613,0.0282733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416802,-0.0147346) , 
4, 0.020289, 1, 0, 0.445673,-0.0453707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410334,-0.00992645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670557,0.0272128) , 
10, 0.768307, 1, 0, 0.601759,0.0848407) , 
11, 0.870647, 1, 0, 0.5,-4.97614e-05)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210786,-0.0376427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449138,-0.00494134) , 
11, 0.741294, 1, 0, 0.289656,-0.12612) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346468,-0.0198944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600547,0.0126884) , 
10, 0.640256, 1, 0, 0.546297,0.0277126) , 
9, 0.650522, 1, 0, 0.5,-3.81687e-05)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221724,-0.0429478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398127,-0.0124433) , 
9, 1.74614, 1, 0, 0.309418,-0.132362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305741,-0.0216319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585111,0.0107611) , 
9, 0.624813, 1, 0, 0.536653,0.0253931) , 
11, 0.0646766, 1, 0, 0.5,-5.27452e-05)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62186,0.0145967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293289,-0.0203956) , 
12, 2.84235, 1, 0, 0.557967,0.0382735) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337153,-0.0243711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541076,0.0120333) , 
1, 0.649067, 1, 0, 0.383652,-0.0770085) , 
3, 0.00415788, 1, 0, 0.5,-6.22625e-05)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645613,0.0261683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416802,-0.0128105) , 
4, 0.020289, 1, 0, 0.445673,-0.0381046) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410334,-0.00758903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670557,0.0228557) , 
10, 0.768307, 1, 0, 0.601759,0.071193) , 
11, 0.870647, 1, 0, 0.5,-6.28976e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340131,-0.0353753) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611187,0.0211783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465259,-0.0059201) , 
7, 2.12561, 1, 0, 0.514904,0.0158042) , 
6, 2.6887, 1, 0, 0.5,-4.93785e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405547,-0.0165763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554728,0.0102113) , 
6, 2.99836, 1, 0, 0.511817,0.012284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290401,-0.045602) , 
6, 3.71998, 1, 0, 0.5,-4.22994e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529022,0.00973001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336405,-0.0239682) , 
4, 0.0695905, 1, 0, 0.404614,-0.0577943) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507568,0.000902647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.838221,0.0447223) , 
10, 2.13127, 1, 0, 0.575044,0.0454007) , 
9, 1.60919, 1, 0, 0.5,-3.83458e-05)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430248,-0.00862935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669434,0.0195581) , 
10, 1.68079, 1, 0, 0.54889,0.0243714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363139,-0.00881002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220493,-0.0367534) , 
10, 1.40866, 1, 0, 0.294905,-0.10231) , 
12, 2.58396, 1, 0, 0.5,-1.37355e-05)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221724,-0.0366077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398127,-0.00975418) , 
9, 1.74614, 1, 0, 0.309418,-0.107366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245208,-0.028252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567005,0.00757243) , 
9, 0.328849, 1, 0, 0.536653,0.0206307) , 
11, 0.0646766, 1, 0, 0.5,-1.51068e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405547,-0.0149657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554728,0.00924938) , 
6, 2.99836, 1, 0, 0.511817,0.0111182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290401,-0.0417045) , 
6, 3.71998, 1, 0, 0.5,-3.06305e-05)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427991,-0.00826796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67557,0.0186747) , 
10, 1.68079, 1, 0, 0.550684,0.0227444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351026,-0.00795029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242059,-0.0340806) , 
4, 0.0777973, 1, 0, 0.306093,-0.0871588) , 
12, 2.49782, 1, 0, 0.5,-2.95571e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529022,0.00899416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336405,-0.0219645) , 
4, 0.0695905, 1, 0, 0.404614,-0.0521046) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615045,0.0148956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323297,-0.0300058) , 
9, 4.02254, 1, 0, 0.575044,0.0409462) , 
9, 1.60919, 1, 0, 0.5,-2.61345e-05)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645613,0.0223447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416802,-0.0109886) , 
4, 0.020289, 1, 0, 0.445673,-0.0321976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380876,-0.0101002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652408,0.018111) , 
10, 0.512205, 1, 0, 0.601759,0.0602253) , 
11, 0.870647, 1, 0, 0.5,-2.91896e-05)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404666,-0.0139611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.559495,0.00967398) , 
6, 2.99652, 1, 0, 0.513798,0.0129428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34463,-0.0313172) , 
6, 3.56372, 1, 0, 0.5,-2.13451e-05)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529022,0.00789465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336405,-0.0198291) , 
4, 0.0695905, 1, 0, 0.404614,-0.0469239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39558,-0.0245679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613505,0.0148254) , 
8, 2.37646, 1, 0, 0.575044,0.0368801) , 
9, 1.60919, 1, 0, 0.5,-2.06344e-05)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43078,-0.00683103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667746,0.0160675) , 
10, 1.68079, 1, 0, 0.547765,0.0195704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35737,-0.00611959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209191,-0.0342275) , 
10, 1.40875, 1, 0, 0.285384,-0.0880501) , 
12, 2.67009, 1, 0, 0.5,-2.12429e-05)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340131,-0.0283763) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611187,0.0181353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465259,-0.0052705) , 
7, 2.12561, 1, 0, 0.514904,0.0124078) , 
6, 2.6887, 1, 0, 0.5,-2.36376e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47995,-0.00264761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628629,0.0193924) , 
8, 3.56332, 1, 0, 0.511817,0.00949925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290401,-0.0364513) , 
6, 3.71998, 1, 0, 0.5,-2.06322e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645613,0.0208748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416802,-0.00982335) , 
4, 0.020289, 1, 0, 0.445673,-0.0280714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380876,-0.00871298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652408,0.0159946) , 
10, 0.512205, 1, 0, 0.601759,0.0525271) , 
11, 0.870647, 1, 0, 0.5,-1.85771e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529022,0.00719874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336405,-0.0183389) , 
4, 0.0695905, 1, 0, 0.404614,-0.0431036) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615045,0.0127692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323297,-0.026451) , 
9, 4.02254, 1, 0, 0.575044,0.0338894) , 
9, 1.60919, 1, 0, 0.5,-1.2354e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431309,-0.00887245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571211,0.0102056) , 
6, 3.06742, 1, 0, 0.513798,0.0111427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34463,-0.0275324) , 
6, 3.56372, 1, 0, 0.5,-1.65648e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427991,-0.00649103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67557,0.015581) , 
10, 1.68079, 1, 0, 0.550684,0.0189515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375655,-0.00391756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231805,-0.0299589) , 
10, 1.40856, 1, 0, 0.306093,-0.0725824) , 
12, 2.49782, 1, 0, 0.5,-1.60367e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340131,-0.0253668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611187,0.0157155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465259,-0.00441642) , 
7, 2.12561, 1, 0, 0.514904,0.0109664) , 
6, 2.6887, 1, 0, 0.5,-1.67159e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416129,-0.00570974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217647,-0.0293171) , 
4, 0.14469, 1, 0, 0.309418,-0.0803023) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305741,-0.0149562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585111,0.0070397) , 
9, 0.624813, 1, 0, 0.536653,0.0154263) , 
11, 0.0646766, 1, 0, 0.5,-1.4697e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670939,0.0222951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341865,-0.0244771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496706,0.000326539) , 
6, 2.8137, 1, 0, 0.478065,-0.012273) , 
4, 0.020289, 1, 0, 0.5,-2.47667e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463088,-0.0054023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627565,0.0129972) , 
9, 2.00749, 1, 0, 0.534257,0.0121757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221068,-0.0236374) , 
12, 3.22994, 1, 0, 0.5,-2.15767e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333029,-0.0136935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561807,0.00659474) , 
10, 0.672269, 1, 0, 0.513798,0.0102744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34463,-0.0258094) , 
6, 3.56372, 1, 0, 0.5,-2.46397e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548548,0.00768299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399813,-0.0111156) , 
12, 0.818253, 1, 0, 0.445673,-0.0239407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677343,0.0188007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530054,0.001639) , 
3, 0.00183706, 1, 0, 0.601759,0.0447679) , 
11, 0.870647, 1, 0, 0.5,-2.62086e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642945,0.0158269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440301,-0.00542457) , 
4, 0.0695905, 1, 0, 0.514676,0.00926448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326768,-0.0237059) , 
9, 4.00584, 1, 0, 0.5,-2.11461e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500587,-0.000313434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69237,0.0337358) , 
1, 0.758119, 1, 0, 0.511817,0.00754923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290401,-0.0301281) , 
6, 3.71998, 1, 0, 0.5,-1.67289e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444171,0.00342147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295161,-0.0178783) , 
4, 0.0548, 1, 0, 0.344068,-0.0481827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385279,-0.0268035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587183,0.0082626) , 
8, 2.188, 1, 0, 0.566557,0.0205437) , 
9, 1.09562, 1, 0, 0.5,-1.56791e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864794,0.0392747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513997,5.72287e-05) , 
4, 0.020289, 1, 0, 0.54414,0.0135783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341876,-0.00331319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185231,-0.0320224) , 
10, 1.31272, 1, 0, 0.264879,-0.0724472) , 
12, 2.84235, 1, 0, 0.5,-1.88222e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308221,-0.0266504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527885,0.00398981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344006,-0.0228519) , 
6, 3.5628, 1, 0, 0.511899,0.00748743) , 
6, 2.5637, 1, 0, 0.5,-1.06134e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567509,0.00687391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416543,-0.0129106) , 
7, 2.11766, 1, 0, 0.48643,-0.0170548) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687341,0.0266059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42326,-0.000576714) , 
3, 0.0012478, 1, 0, 0.541654,0.0522973) , 
7, 4.78263, 1, 0, 0.5,-1.37357e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.227622,-0.0283693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417714,-0.00350121) , 
9, 2.02004, 1, 0, 0.306773,-0.0761902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567236,0.00502362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227351,-0.0190229) , 
12, 3.22994, 1, 0, 0.529059,0.0114476) , 
11, 0.0447761, 1, 0, 0.5,-8.99216e-06)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473614,-0.0069406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523506,0.00921236) , 
7, 4.47004, 1, 0, 0.490337,-0.00714139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66357,0.0270483) , 
1, 0.762621, 1, 0, 0.5,-1.99024e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339496,-0.0174537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490526,0.000497189) , 
6, 3.00121, 1, 0, 0.445673,-0.0205514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410334,-0.00388661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670557,0.0133423) , 
10, 0.768307, 1, 0, 0.601759,0.0384468) , 
11, 0.870647, 1, 0, 0.5,-1.67041e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505049,0.0159302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397125,-0.0126874) , 
8, 2.65588, 1, 0, 0.419542,-0.029322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39323,-0.0188669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613008,0.0114331) , 
8, 2.37798, 1, 0, 0.573913,0.0269086) , 
9, 1.74614, 1, 0, 0.5,-1.46821e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330928,-0.0119898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558376,0.00529134) , 
10, 0.640256, 1, 0, 0.512186,0.00758247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332281,-0.0239213) , 
6, 3.62622, 1, 0, 0.5,-1.45522e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670939,0.0186586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341865,-0.0210115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496706,0.00042779) , 
6, 2.8137, 1, 0, 0.478065,-0.00966008) , 
4, 0.020289, 1, 0, 0.5,-1.67982e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428634,-0.00544776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678392,0.0132336) , 
10, 1.70089, 1, 0, 0.551124,0.0147512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375149,-0.00170962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255141,-0.0254497) , 
4, 0.0777973, 1, 0, 0.325028,-0.0505526) , 
12, 2.36863, 1, 0, 0.5,-1.50045e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556598,0.0106008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361723,-0.013396) , 
4, 0.0548, 1, 0, 0.419542,-0.0285692) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617402,0.0105772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323568,-0.0203925) , 
9, 4.0202, 1, 0, 0.573913,0.0262179) , 
9, 1.74614, 1, 0, 0.5,-1.42733e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489371,-0.00116959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652531,0.0190496) , 
8, 3.71961, 1, 0, 0.512186,0.00706303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332281,-0.0225326) , 
6, 3.62622, 1, 0, 0.5,-1.59794e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559749,0.0081531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414405,-0.00855714) , 
12, 0.732121, 1, 0, 0.454865,-0.0171288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655351,0.013504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435533,-0.00516706) , 
3, 0.00734825, 1, 0, 0.602241,0.038756) , 
11, 0.910448, 1, 0, 0.5,-1.36727e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473614,-0.00629507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523506,0.00847668) , 
7, 4.47004, 1, 0, 0.490337,-0.0062152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66357,0.0240545) , 
1, 0.762621, 1, 0, 0.5,-1.04089e-05)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501592,-0.00213077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72394,0.0334761) , 
9, 2.26269, 1, 0, 0.576954,0.0435575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435378,-0.0115089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522691,0.00733565) , 
7, 4.46476, 1, 0, 0.473149,-0.0152094) , 
7, 1.65673, 1, 0, 0.5,-8.16511e-06)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436162,-0.00474426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680303,0.01264) , 
10, 1.75759, 1, 0, 0.551124,0.013401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375149,-0.00164646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255141,-0.0233666) , 
4, 0.0777973, 1, 0, 0.325028,-0.0458759) , 
12, 2.36863, 1, 0, 0.5,-2.43146e-06)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269341,-0.0376421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485191,0.00808944) , 
7, 3.25075, 1, 0, 0.375232,-0.0657815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634173,0.0188544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480622,-0.00311652) , 
7, 1.65673, 1, 0, 0.517984,0.00947862) , 
6, 2.8137, 1, 0, 0.5,-2.83062e-06)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271937,-0.0216446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355786,0.00116862) , 
1, 0.39217, 1, 0, 0.308851,-0.0477625) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381575,-0.0197157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570809,0.00557786) , 
8, 2.188, 1, 0, 0.551982,0.012983) , 
9, 0.787474, 1, 0, 0.5,-4.48398e-06)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48933,-0.000996222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672199,0.0195248) , 
8, 3.71961, 1, 0, 0.513798,0.00738817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34463,-0.0195997) , 
6, 3.56372, 1, 0, 0.5,-9.71017e-06)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.227622,-0.0247084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417714,-0.0022348) , 
9, 2.02004, 1, 0, 0.306773,-0.0620063) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242626,-0.0187251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558536,0.00411808) , 
9, 0.328849, 1, 0, 0.529059,0.00931636) , 
11, 0.0447761, 1, 0, 0.5,-7.39669e-06)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47298,-0.00579928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523279,0.00756257) , 
7, 4.47004, 1, 0, 0.48987,-0.00593059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660711,0.0217434) , 
1, 0.758119, 1, 0, 0.5,-1.57566e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463088,-0.00424568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627565,0.00967093) , 
9, 2.00749, 1, 0, 0.534257,0.00802861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221068,-0.0169332) , 
12, 3.22994, 1, 0, 0.5,-1.29809e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670939,0.0165701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465591,-0.0202379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479473,0.000175122) , 
4, 0.0299554, 1, 0, 0.478065,-0.00821648) , 
4, 0.020289, 1, 0, 0.5,-1.4313e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577959,0.00817936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342657,-0.0128973) , 
4, 0.0695905, 1, 0, 0.427469,-0.0231432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601968,0.00892762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393807,-0.014738) , 
9, 3.57439, 1, 0, 0.57092,0.0226101) , 
11, 0.671642, 1, 0, 0.5,-9.64936e-06)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431544,-0.0063514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56682,0.00664763) , 
6, 3.06712, 1, 0, 0.512186,0.00618658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332281,-0.0201571) , 
6, 3.62622, 1, 0, 0.5,-1.12262e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501592,-0.00211073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72394,0.0295255) , 
9, 2.26269, 1, 0, 0.576954,0.0365784) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41544,-0.00887155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58307,0.00939341) , 
10, 2.14486, 1, 0, 0.473149,-0.0127786) , 
7, 1.65673, 1, 0, 0.5,-1.14037e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308221,-0.0201782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528601,0.00404654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434655,-0.0118358) , 
6, 3.35928, 1, 0, 0.511899,0.0053749) , 
6, 2.5637, 1, 0, 0.5,-5.45849e-06)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320709,-0.0146769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595401,0.00615661) , 
10, 0.65201, 1, 0, 0.551124,0.0116064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388055,0.000130749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.249617,-0.0222667) , 
10, 1.63265, 1, 0, 0.325028,-0.0397541) , 
12, 2.36863, 1, 0, 0.5,-7.01311e-06)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56433,0.00508764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420553,-0.00697057) , 
3, 0.00155756, 1, 0, 0.490337,-0.00518517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66357,0.0205596) , 
1, 0.762621, 1, 0, 0.5,-1.31134e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427774,-0.00585666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605086,0.00898178) , 
11, 0.671642, 1, 0, 0.514676,0.00615792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326768,-0.0166452) , 
9, 4.00584, 1, 0, 0.5,-1.1076e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567955,0.00564561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416512,-0.0109895) , 
7, 2.13183, 1, 0, 0.490251,-0.012864) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355368,-0.00815557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601145,0.0145464) , 
6, 2.99977, 1, 0, 0.525313,0.0333625) , 
7, 4.65759, 1, 0, 0.5,-1.05494e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506365,0.0185134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378573,-0.0117483) , 
8, 2.65588, 1, 0, 0.404614,-0.0230771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507568,-0.000108717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.838221,0.0260579) , 
10, 2.13127, 1, 0, 0.575044,0.0181385) , 
9, 1.60919, 1, 0, 0.5,-9.65792e-06)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269341,-0.0339999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485191,0.00924226) , 
7, 3.25075, 1, 0, 0.375232,-0.0533209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634173,0.0166063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480622,-0.00285874) , 
7, 1.65673, 1, 0, 0.517984,0.00768541) , 
6, 2.8137, 1, 0, 0.5,-3.05303e-07)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48933,-0.000949126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672199,0.0171462) , 
8, 3.71961, 1, 0, 0.513798,0.00599982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34463,-0.0164167) , 
6, 3.56372, 1, 0, 0.5,-2.50036e-06)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573013,0.00570409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428389,-0.00815948) , 
7, 1.87972, 1, 0, 0.48643,-0.0112314) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628876,0.0231551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484734,-0.00190227) , 
7, 5.41718, 1, 0, 0.541654,0.0344727) , 
7, 4.78263, 1, 0, 0.5,-1.11676e-06)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563593,0.00469072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420578,-0.00648395) , 
3, 0.00153927, 1, 0, 0.48987,-0.00495155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660711,0.0186503) , 
1, 0.758119, 1, 0, 0.5,-4.02758e-07)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278429,-0.0183603) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243201,-0.0150289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543022,0.00271263) , 
9, 0.328849, 1, 0, 0.515561,0.00517534) , 
11, 0.0149254, 1, 0, 0.5,2.99356e-07)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693865,0.0251759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499213,-0.000718783) , 
0, 0.400427, 1, 0, 0.514676,0.00555619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326768,-0.015187) , 
9, 4.00584, 1, 0, 0.5,-4.47012e-06)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670939,0.014427) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465591,-0.0187999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479473,0.000320989) , 
4, 0.0299554, 1, 0, 0.478065,-0.00685186) , 
4, 0.020289, 1, 0, 0.5,-2.80805e-06)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533996,0.0164803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420073,-0.00976113) , 
8, 2.65588, 1, 0, 0.444114,-0.0171903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367226,-0.0178359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613518,0.010123) , 
8, 2.37798, 1, 0, 0.56771,0.0208267) , 
9, 2.02004, 1, 0, 0.5,-2.43491e-07)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396305,-0.0158234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474037,0.00841046) , 
7, 4.00092, 1, 0, 0.428819,-0.0248246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634958,0.0158035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476866,-0.00484404) , 
7, 2.53198, 1, 0, 0.542254,0.0147337) , 
6, 3.06371, 1, 0, 0.5,-1.57089e-06)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430742,-0.00517553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581202,0.00879118) , 
6, 3.06651, 1, 0, 0.510657,0.00967922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504121,0.00183241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376944,-0.0274892) , 
0, 0.766468, 1, 0, 0.457056,-0.0390044) , 
6, 3.31372, 1, 0, 0.5,-4.69708e-07)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293219,-0.0180555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3688,0.00219571) , 
12, 2.05911, 1, 0, 0.327602,-0.0382937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580522,0.00470933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205254,-0.0221175) , 
12, 3.05768, 1, 0, 0.542919,0.00953277) , 
10, 0.640256, 1, 0, 0.5,-3.73899e-07)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576139,0.00659491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442825,-0.00782305) , 
7, 1.64521, 1, 0, 0.490251,-0.0116206) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355368,-0.00796728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601145,0.0134838) , 
6, 2.99977, 1, 0, 0.525313,0.0301418) , 
7, 4.65759, 1, 0, 0.5,-8.38777e-06)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47995,-0.00169255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628629,0.011419) , 
8, 3.56332, 1, 0, 0.511817,0.00441602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290401,-0.0193957) , 
6, 3.71998, 1, 0, 0.5,-7.03271e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670939,0.0139976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570952,0.00645431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435581,-0.00510751) , 
12, 0.755757, 1, 0, 0.478065,-0.00652648) , 
4, 0.020289, 1, 0, 0.5,-6.63643e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533996,0.0156261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420073,-0.00932831) , 
8, 2.65588, 1, 0, 0.444114,-0.016338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519836,-0.0180742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579122,0.00953084) , 
4, 0.0221273, 1, 0, 0.56771,0.0197841) , 
9, 2.02004, 1, 0, 0.5,-4.73655e-06)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278429,-0.0170615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4908,-0.00167006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582761,0.00970733) , 
10, 2.497, 1, 0, 0.515561,0.00472591) , 
11, 0.0149254, 1, 0, 0.5,-4.11172e-06)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436162,-0.00369663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680303,0.0097782) , 
10, 1.75759, 1, 0, 0.551124,0.00951873) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375149,0.000833007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255141,-0.0203593) , 
4, 0.0777973, 1, 0, 0.325028,-0.0326002) , 
12, 2.36863, 1, 0, 0.5,-5.00044e-06)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533996,0.0134778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420073,-0.00879943) , 
8, 2.65588, 1, 0, 0.444114,-0.016411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519836,-0.016436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579122,0.00924381) , 
4, 0.0221273, 1, 0, 0.56771,0.0198699) , 
9, 2.02004, 1, 0, 0.5,-5.89156e-06)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670939,0.0137257) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341865,-0.0153003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496706,0.000389216) , 
6, 2.8137, 1, 0, 0.478065,-0.00637682) , 
4, 0.020289, 1, 0, 0.5,-5.09852e-06)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58666,0.00841255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424295,-0.00465573) , 
3, 0.00207894, 1, 0, 0.510657,0.00881218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504121,0.00156719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376944,-0.0250694) , 
0, 0.766468, 1, 0, 0.457056,-0.0355328) , 
6, 3.31372, 1, 0, 0.5,-4.87518e-06)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567955,0.00442674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416512,-0.0089839) , 
7, 2.13183, 1, 0, 0.490251,-0.0106461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355368,-0.00763278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601145,0.0125896) , 
6, 2.99977, 1, 0, 0.525313,0.0276258) , 
7, 4.65759, 1, 0, 0.5,-4.46239e-06)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459133,-0.00326884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790669,0.0228516) , 
10, 2.00204, 1, 0, 0.588946,0.0246271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331163,-0.0191947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47787,-0.000136659) , 
8, 2.31334, 1, 0, 0.45779,-0.0116931) , 
12, 0.818253, 1, 0, 0.5,-4.16398e-06)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342681,-0.0142702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484737,0.0025586) , 
6, 3.06371, 1, 0, 0.427469,-0.017037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571376,0.0158772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57077,0.000314398) , 
11, 0.859608, 1, 0, 0.57092,0.0166633) , 
11, 0.671642, 1, 0, 0.5,2.34913e-06)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430742,-0.00399411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581202,0.00740134) , 
6, 3.06651, 1, 0, 0.510657,0.00867074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589229,0.007896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380762,-0.0177833) , 
7, 2.28191, 1, 0, 0.457056,-0.0349398) , 
6, 3.31372, 1, 0, 0.5,-2.77368e-07)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328266,-0.0102619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473327,0.00807067) , 
10, 3.20128, 1, 0, 0.360439,-0.0242806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606971,0.00521391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209166,-0.0204742) , 
12, 3.40221, 1, 0, 0.566602,0.011586) , 
9, 1.19833, 1, 0, 0.5,-8.87641e-07)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670939,0.0126579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465591,-0.0162979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479473,0.00028359) , 
4, 0.0299554, 1, 0, 0.478065,-0.00577113) , 
4, 0.020289, 1, 0, 0.5,-6.46781e-06)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503909,-0.000282543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377262,-0.0191391) , 
7, 4.37951, 1, 0, 0.490251,-0.00992559) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512433,0.00173722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571632,0.0233994) , 
9, 2.84175, 1, 0, 0.525313,0.0257553) , 
7, 4.65759, 1, 0, 0.5,-4.38276e-06)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.320709,-0.0119581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595401,0.00497481) , 
10, 0.65201, 1, 0, 0.551124,0.00884515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295074,-0.0149787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388193,0.00697397) , 
9, 3.62923, 1, 0, 0.325028,-0.0302961) , 
12, 2.36863, 1, 0, 0.5,-5.28349e-06)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614082,0.00747772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447432,-0.00257458) , 
4, 0.0695905, 1, 0, 0.512186,0.00437343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332281,-0.014996) , 
6, 3.62622, 1, 0, 0.5,-9.05964e-06)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49919,0.0145969) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352091,-0.0178531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514925,0.000676509) , 
6, 2.8149, 1, 0, 0.500057,-0.00423156) , 
8, 2.15675, 1, 0, 0.5,-8.23607e-06)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278429,-0.0152382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63308,0.0122765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499916,-0.000443711) , 
12, 0.301461, 1, 0, 0.515561,0.00410058) , 
11, 0.0149254, 1, 0, 0.5,-9.26808e-06)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58666,0.00716387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424295,-0.00377766) , 
3, 0.00207894, 1, 0, 0.510657,0.00771036) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504121,0.00180495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376944,-0.0228957) , 
0, 0.766468, 1, 0, 0.457056,-0.0311142) , 
6, 3.31372, 1, 0, 0.5,-9.0757e-06)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540963,0.00589203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526184,-0.00436754) , 
6, 3.15746, 1, 0, 0.534257,0.00530145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221068,-0.0120906) , 
12, 3.22994, 1, 0, 0.5,-8.52006e-06)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308221,-0.0154348) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62625,0.0123372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492111,-0.000991529) , 
7, 1.06281, 1, 0, 0.511899,0.00388059) , 
6, 2.5637, 1, 0, 0.5,-9.65504e-06)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443356,-0.00729599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574375,0.00641792) , 
8, 3.56332, 1, 0, 0.489553,-0.0105521) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757301,0.0272377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470259,0.00127246) , 
4, 0.029916, 1, 0, 0.522238,0.0224334) , 
7, 4.47004, 1, 0, 0.5,-8.90396e-06)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533996,0.0141603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420073,-0.00829222) , 
8, 2.65588, 1, 0, 0.444114,-0.0139096) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519836,-0.0165773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579122,0.00843054) , 
4, 0.0221273, 1, 0, 0.56771,0.0168429) , 
9, 2.02004, 1, 0, 0.5,-4.30398e-06)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577959,0.0068458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342657,-0.00947175) , 
4, 0.0695905, 1, 0, 0.427469,-0.0149899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601968,0.00625836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393807,-0.0107493) , 
9, 3.57439, 1, 0, 0.57092,0.0146492) , 
11, 0.671642, 1, 0, 0.5,-3.92154e-06)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67811,0.0145336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468579,-0.00239909) , 
4, 0.0195712, 1, 0, 0.490337,-0.00357971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66357,0.0149597) , 
1, 0.762621, 1, 0, 0.5,-5.11264e-06)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314619,-0.0112249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595881,0.0046916) , 
10, 0.65201, 1, 0, 0.551163,0.0084198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384484,-0.000867629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197175,-0.0272815) , 
3, 0.00374339, 1, 0, 0.340113,-0.0263238) , 
12, 2.28249, 1, 0, 0.5,-2.7463e-06)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503375,-0.00176246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723738,0.0226072) , 
9, 2.29548, 1, 0, 0.576954,0.0249349) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435378,-0.00747253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522691,0.0049799) , 
7, 4.46476, 1, 0, 0.473149,-0.00871185) , 
7, 1.65673, 1, 0, 0.5,-8.44461e-06)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319466,-0.013977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642076,0.0139607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496807,-0.000572368) , 
7, 0.812735, 1, 0, 0.512206,0.00380299) , 
6, 2.59495, 1, 0, 0.5,-4.62187e-06)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492873,-0.000865786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664696,0.0154978) , 
8, 3.81338, 1, 0, 0.511817,0.00349107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290401,-0.0159038) , 
6, 3.71998, 1, 0, 0.5,-4.15893e-06)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49919,0.0135282) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352091,-0.0165646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514925,0.000619919) , 
6, 2.8149, 1, 0, 0.500057,-0.0038724) , 
8, 2.15675, 1, 0, 0.5,-3.39941e-06)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430742,-0.0038703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581202,0.00662818) , 
6, 3.06651, 1, 0, 0.510657,0.00704189) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504121,0.00164237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376944,-0.0211303) , 
0, 0.766468, 1, 0, 0.457056,-0.0283984) , 
6, 3.31372, 1, 0, 0.5,-4.65624e-06)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448251,-0.0034551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60586,0.00646095) , 
9, 2.01119, 1, 0, 0.516947,0.00356829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238779,-0.0144058) , 
12, 3.57447, 1, 0, 0.5,-4.76037e-06)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456474,-0.0168894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478142,0.000287494) , 
4, 0.0301493, 1, 0, 0.475168,-0.00804397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831326,0.0292984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43434,-0.00437102) , 
12, 1.20585, 1, 0, 0.569989,0.0226515) , 
10, 2.497, 1, 0, 0.5,-5.34729e-06)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670939,0.011254) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465591,-0.0150997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479473,0.000338608) , 
4, 0.0299554, 1, 0, 0.478065,-0.00490844) , 
4, 0.020289, 1, 0, 0.5,5.03156e-06)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361937,0.000871317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269022,-0.0157238) , 
12, 1.03223, 1, 0, 0.306773,-0.0346071) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551252,0.01725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527552,0.000183597) , 
8, 2.15675, 1, 0, 0.529059,0.00521079) , 
11, 0.0447761, 1, 0, 0.5,5.52978e-06)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503909,-2.29604e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377262,-0.018272) , 
7, 4.37951, 1, 0, 0.490251,-0.00837255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512433,0.00108321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571632,0.0217477) , 
9, 2.84175, 1, 0, 0.525313,0.0217483) , 
7, 4.65759, 1, 0, 0.5,2.66132e-06)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503375,-0.00152956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723738,0.0205474) , 
9, 2.29548, 1, 0, 0.576954,0.0223822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41544,-0.00596879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58307,0.00679621) , 
10, 2.14486, 1, 0, 0.473149,-0.00780807) , 
7, 1.65673, 1, 0, 0.5,1.23623e-06)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314619,-0.01047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595881,0.00432882) , 
10, 0.65201, 1, 0, 0.551163,0.00758825) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314572,-0.0128718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397642,0.00824852) , 
9, 3.62923, 1, 0, 0.340113,-0.0236977) , 
12, 2.28249, 1, 0, 0.5,3.90976e-06)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47995,-0.00155774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628629,0.00962438) , 
8, 3.56332, 1, 0, 0.511817,0.00311322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290401,-0.0143808) , 
6, 3.71998, 1, 0, 0.5,1.33567e-07)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47201,-0.00452095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617071,0.0130739) , 
11, 0.99005, 1, 0, 0.489553,-0.00927137) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757301,0.0246998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470259,0.00115455) , 
4, 0.029916, 1, 0, 0.522238,0.0197354) , 
7, 4.47004, 1, 0, 0.5,8.47047e-08)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359342,-0.0121781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506154,0.000633288) , 
8, 2.31303, 1, 0, 0.490337,-0.00315877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66357,0.0134648) , 
1, 0.762621, 1, 0, 0.5,3.70233e-06)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49919,0.0123956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418017,-0.00735524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542348,0.00241563) , 
6, 3.06482, 1, 0, 0.500057,-0.00350746) , 
8, 2.15675, 1, 0, 0.5,2.88715e-06)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23185,-0.0140031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54213,0.00329153) , 
9, 0.34238, 1, 0, 0.510657,0.00675812) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589229,0.00707527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380762,-0.014727) , 
7, 2.28191, 1, 0, 0.457056,-0.0272227) , 
6, 3.31372, 1, 0, 0.5,1.76493e-06)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317108,-0.00935852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562141,0.0022672) , 
9, 1.09562, 1, 0, 0.493692,-0.00355472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58435,0.0131651) , 
10, 3.48939, 1, 0, 0.5,-1.34318e-06)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505351,-0.000233137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706745,0.0192168) , 
1, 0.758119, 1, 0, 0.516947,0.00340457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238779,-0.0138822) , 
12, 3.57447, 1, 0, 0.5,-2.94941e-06)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576139,0.00511786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442825,-0.00594455) , 
7, 1.64521, 1, 0, 0.490251,-0.00824662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571097,0.0142669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485298,-0.00224509) , 
7, 5.41779, 1, 0, 0.525313,0.021402) , 
7, 4.65759, 1, 0, 0.5,-2.70679e-06)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319466,-0.0125637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515289,0.00465919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508467,-0.00378449) , 
6, 3.16368, 1, 0, 0.512206,0.00336435) , 
6, 2.59495, 1, 0, 0.5,-2.38659e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370153,-0.0105795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.798837,0.026382) , 
10, 1.59741, 1, 0, 0.613807,0.0340658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580374,0.00482496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419269,-0.00480929) , 
4, 0.0695905, 1, 0, 0.484811,-0.00454986) , 
12, 0.301461, 1, 0, 0.5,-2.98112e-06)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45862,0.00645579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407911,-0.0091957) , 
8, 2.93772, 1, 0, 0.427469,-0.012461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571376,0.014085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57077,-0.00036248) , 
11, 0.859608, 1, 0, 0.57092,0.0121889) , 
11, 0.671642, 1, 0, 0.5,2.35094e-06)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54625,0.00540793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528532,-0.00400219) , 
6, 3.15746, 1, 0, 0.53818,0.00470886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240809,-0.00897499) , 
12, 3.05768, 1, 0, 0.5,1.19694e-06)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526165,0.0173473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406311,-0.00938497) , 
8, 2.28178, 1, 0, 0.428819,-0.0165661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634958,0.012076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476866,-0.00398975) , 
7, 2.53198, 1, 0, 0.542254,0.00983387) , 
6, 3.06371, 1, 0, 0.5,-4.91397e-09)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319466,-0.012447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642076,0.0119265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496807,-0.00044673) , 
7, 0.812735, 1, 0, 0.512206,0.00332281) , 
6, 2.59495, 1, 0, 0.5,2.87909e-07)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449607,-0.00709936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511208,0.00171269) , 
1, 0.298895, 1, 0, 0.492664,-0.00367003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590392,0.011304) , 
7, 5.75166, 1, 0, 0.5,2.04626e-07)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443356,-0.00593717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574375,0.00518986) , 
8, 3.56332, 1, 0, 0.489553,-0.00837782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757301,0.0221852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470259,0.0011853) , 
4, 0.029916, 1, 0, 0.522238,0.0178338) , 
7, 4.47004, 1, 0, 0.5,2.24252e-07)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494249,-0.000358085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688882,0.0131829) , 
8, 3.81338, 1, 0, 0.513798,0.0036913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34463,-0.010893) , 
6, 3.56372, 1, 0, 0.5,2.66273e-06)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484247,-0.00251178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549579,0.0123324) , 
9, 2.84175, 1, 0, 0.499472,0.00377902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505657,-0.0101732) , 
1, 0.749114, 1, 0, 0.5,2.98611e-06)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308278,-0.00985115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592663,0.0038) , 
10, 0.595313, 1, 0, 0.551163,0.0068538) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384484,-0.000287279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197175,-0.0246469) , 
3, 0.00374339, 1, 0, 0.340113,-0.0214076) , 
12, 2.28249, 1, 0, 0.5,2.66567e-06)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278429,-0.0123362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4908,-0.00124733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582761,0.00731016) , 
10, 2.497, 1, 0, 0.515561,0.00316115) , 
11, 0.0149254, 1, 0, 0.5,-2.52958e-06)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58719,0.00565601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42542,-0.00312566) , 
3, 0.00207894, 1, 0, 0.511524,0.00548926) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598011,0.0101089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360905,-0.0157954) , 
7, 2.28245, 1, 0, 0.446234,-0.025628) , 
6, 3.34497, 1, 0, 0.5,-2.94562e-06)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448251,-0.00298969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60586,0.00562254) , 
9, 2.01119, 1, 0, 0.516947,0.00303707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238779,-0.0126065) , 
12, 3.57447, 1, 0, 0.5,-3.42629e-06)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503909,-5.95078e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377262,-0.0160383) , 
7, 4.37951, 1, 0, 0.490251,-0.00732446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355368,-0.00781617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601145,0.0100291) , 
6, 2.99977, 1, 0, 0.525313,0.0190034) , 
7, 4.65759, 1, 0, 0.5,-3.91351e-06)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308221,-0.0119081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526994,0.00279594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459157,-0.00657148) , 
6, 3.30378, 1, 0, 0.511899,0.00287242) , 
6, 2.5637, 1, 0, 0.5,-4.13633e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539468,0.00125402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268914,-0.0115661) , 
12, 2.62013, 1, 0, 0.493692,-0.00311833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58435,0.0117993) , 
10, 3.48939, 1, 0, 0.5,-4.56854e-06)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4549,-7.36949e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454588,-0.016418) , 
11, 0.853137, 1, 0, 0.454865,-0.00764427) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669004,0.00968981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487478,-0.00392464) , 
12, 1.7201, 1, 0, 0.602241,0.0172957) , 
11, 0.910448, 1, 0, 0.5,-6.23094e-06)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47201,-0.00386541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617071,0.0114329) , 
11, 0.99005, 1, 0, 0.489553,-0.00762058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513854,0.000555808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550779,0.0168031) , 
9, 2.84175, 1, 0, 0.522238,0.0162077) , 
7, 4.47004, 1, 0, 0.5,-4.33828e-06)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49919,0.0106735) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418017,-0.00670543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542348,0.00226811) , 
6, 3.06482, 1, 0, 0.500057,-0.00297737) , 
8, 2.15675, 1, 0, 0.5,-3.73511e-06)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428313,-0.00324616) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613896,0.013538) , 
6, 3.06324, 1, 0, 0.491385,0.00972285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622357,0.00764602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432493,-0.010579) , 
7, 2.53198, 1, 0, 0.511121,-0.012561) , 
6, 3.15746, 1, 0, 0.5,-4.00002e-06)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64298,0.0127792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471132,-0.00356325) , 
12, 0.301461, 1, 0, 0.489553,-0.00746193) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554859,0.0101085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484734,-0.00295136) , 
7, 5.41714, 1, 0, 0.522238,0.0158751) , 
7, 4.47004, 1, 0, 0.5,-2.69557e-06)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278429,-0.0112559) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4908,-0.0012641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582761,0.00709698) , 
10, 2.497, 1, 0, 0.515561,0.00284897) , 
11, 0.0149254, 1, 0, 0.5,-1.79136e-06)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533996,0.013221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420073,-0.00702019) , 
8, 2.65588, 1, 0, 0.444114,-0.0101459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544277,-0.0126681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576049,0.00794054) , 
2, 0.0152373, 1, 0, 0.56771,0.0122877) , 
9, 2.02004, 1, 0, 0.5,-2.13501e-06)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670939,0.00951474) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465591,-0.0139456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479473,0.000419294) , 
4, 0.0299554, 1, 0, 0.478065,-0.00392759) , 
4, 0.020289, 1, 0, 0.5,-1.85758e-06)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592371,0.011508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539349,-0.0102553) , 
10, 2.38864, 1, 0, 0.575375,0.0192717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418027,-0.00499467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586176,0.00596185) , 
10, 2.14486, 1, 0, 0.475874,-0.00616983) , 
7, 1.56295, 1, 0, 0.5,-1.05174e-06)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502293,0.000359326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383315,-0.014579) , 
7, 5.40825, 1, 0, 0.492664,-0.00308391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590392,0.00966558) , 
7, 5.75166, 1, 0, 0.5,-2.29752e-07)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37527,-0.00881315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324441,0.00834064) , 
3, 0.00831575, 1, 0, 0.360439,-0.0155224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619717,0.0054428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422215,-0.00682337) , 
3, 0.00449692, 1, 0, 0.566602,0.00740715) , 
9, 1.19833, 1, 0, 0.5,-3.87286e-07)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505351,-0.00031521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706745,0.0176723) , 
1, 0.758119, 1, 0, 0.516947,0.00270055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238779,-0.0113594) , 
12, 3.57447, 1, 0, 0.5,-1.57178e-06)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311098,-0.0100107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539446,0.00110967) , 
10, 0.768307, 1, 0, 0.48643,-0.00605031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498963,-0.000702976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672941,0.0204746) , 
9, 2.60209, 1, 0, 0.541654,0.0185679) , 
7, 4.78263, 1, 0, 0.5,-1.1818e-06)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460852,-0.00667702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526239,0.00604653) , 
0, 0.601338, 1, 0, 0.503586,0.0062857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42684,-0.0149045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56432,0.00824435) , 
1, 0.454681, 1, 0, 0.490071,-0.0174106) , 
6, 3.25121, 1, 0, 0.5,-1.39023e-06)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319466,-0.0106186) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642076,0.0110295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496807,-0.000488596) , 
7, 0.812735, 1, 0, 0.512206,0.00277282) , 
6, 2.59495, 1, 0, 0.5,-1.67531e-06)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42121,-0.00871983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.663084,0.00984877) , 
10, 1.6013, 1, 0, 0.594166,0.0127345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44539,-0.0213609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436936,0.000601286) , 
2, 0.0442759, 1, 0, 0.437957,-0.00839278) , 
4, 0.0695905, 1, 0, 0.5,-1.45475e-06)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317622,0.000231919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225744,-0.0149651) , 
7, 3.49961, 1, 0, 0.266312,-0.0284415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536789,0.00472845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526359,-0.00362439) , 
6, 3.15746, 1, 0, 0.53209,0.00390653) , 
9, 0.445094, 1, 0, 0.5,8.26456e-07)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485716,0.00283062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465808,-0.00689582) , 
8, 2.96053, 1, 0, 0.476894,-0.00588547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643169,0.0119409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427195,-0.00990514) , 
8, 4.10449, 1, 0, 0.572999,0.01859) , 
8, 3.56332, 1, 0, 0.5,-9.46374e-07)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457932,0.0105296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.312648,-0.0204147) , 
8, 2.46932, 1, 0, 0.375232,-0.0274107) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634578,0.0103056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483887,-0.00162042) , 
7, 1.56295, 1, 0, 0.517984,0.00395097) , 
6, 2.8137, 1, 0, 0.5,-4.69887e-08)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311098,-0.00908293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539446,0.000862623) , 
10, 0.768307, 1, 0, 0.48643,-0.00586482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498963,-0.000406115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672941,0.0191851) , 
9, 2.60209, 1, 0, 0.541654,0.0179985) , 
7, 4.78263, 1, 0, 0.5,-1.17128e-06)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37527,-0.00823955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324441,0.00762626) , 
3, 0.00831575, 1, 0, 0.360439,-0.0145278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606971,0.00344192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209166,-0.0143155) , 
12, 3.40221, 1, 0, 0.566602,0.00693125) , 
9, 1.19833, 1, 0, 0.5,-1.21449e-06)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317108,-0.00767425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562141,0.00189072) , 
9, 1.09562, 1, 0, 0.493692,-0.00278329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58435,0.0107103) , 
10, 3.48939, 1, 0, 0.5,-4.21788e-06)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404772,-0.00642511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50298,0.0101852) , 
9, 2.77328, 1, 0, 0.427469,-0.0100957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571376,0.0129798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57077,-0.000664804) , 
11, 0.859608, 1, 0, 0.57092,0.00986172) , 
11, 0.671642, 1, 0, 0.5,-4.94106e-06)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308221,-0.0104656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526994,0.00235699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459157,-0.00542827) , 
6, 3.30378, 1, 0, 0.511899,0.00246854) , 
6, 2.5637, 1, 0, 0.5,-5.02001e-06)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456474,-0.0139317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478142,0.000284354) , 
4, 0.0301493, 1, 0, 0.475168,-0.0059771) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.831326,0.0237561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43434,-0.0032416) , 
12, 1.20585, 1, 0, 0.569989,0.0168267) , 
10, 2.497, 1, 0, 0.5,-5.18812e-06)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670939,0.00924716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465591,-0.0126146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479473,0.000315763) , 
4, 0.0299554, 1, 0, 0.478065,-0.00369724) , 
4, 0.020289, 1, 0, 0.5,1.31589e-06)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481049,-0.0075346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.657439,0.0097982) , 
8, 2.68831, 1, 0, 0.594166,0.0122422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44539,-0.0194072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436936,0.000408341) , 
2, 0.0442759, 1, 0, 0.437957,-0.00806323) , 
4, 0.0695905, 1, 0, 0.5,1.67065e-06)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47201,-0.0034682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617071,0.0101822) , 
11, 0.99005, 1, 0, 0.489553,-0.00671089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59429,0.00730804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3071,-0.00788097) , 
12, 2.35687, 1, 0, 0.522238,0.014295) , 
7, 4.47004, 1, 0, 0.5,3.24653e-06)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359342,-0.0106785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506154,0.00062052) , 
8, 2.31303, 1, 0, 0.490337,-0.002397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66357,0.0106488) , 
1, 0.762621, 1, 0, 0.5,3.19532e-06)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49919,0.00981582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418017,-0.00593111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542348,0.00196176) , 
6, 3.06482, 1, 0, 0.500057,-0.00268932) , 
8, 2.15675, 1, 0, 0.5,2.41756e-06)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278429,-0.010354) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4908,-0.00109029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582761,0.00637244) , 
10, 2.497, 1, 0, 0.515561,0.00257018) , 
11, 0.0149254, 1, 0, 0.5,1.65407e-06)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460852,-0.00579519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526239,0.00536198) , 
0, 0.601338, 1, 0, 0.503586,0.00571619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42684,-0.0138329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56432,0.00774852) , 
1, 0.454681, 1, 0, 0.490071,-0.0158245) , 
6, 3.25121, 1, 0, 0.5,1.02651e-06)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533996,0.012603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420073,-0.00639965) , 
8, 2.65588, 1, 0, 0.444114,-0.00861586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544277,-0.0105532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576049,0.00667617) , 
2, 0.0152373, 1, 0, 0.56771,0.0104398) , 
9, 2.02004, 1, 0, 0.5,4.94853e-07)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481049,-0.00667225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.657439,0.00923558) , 
8, 2.68831, 1, 0, 0.594166,0.0120478) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560312,0.0126224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416804,-0.00442995) , 
12, 0.336695, 1, 0, 0.437957,-0.0079375) , 
4, 0.0695905, 1, 0, 0.5,2.7331e-07)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49919,0.00887685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418017,-0.00558925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542348,0.00188652) , 
6, 3.06482, 1, 0, 0.500057,-0.00243563) , 
8, 2.15675, 1, 0, 0.5,1.26173e-06)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592371,0.0102187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539349,-0.00954621) , 
10, 2.38864, 1, 0, 0.575375,0.0164619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487987,0.00214166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454979,-0.00751469) , 
8, 3.09446, 1, 0, 0.475874,-0.00526818) , 
7, 1.56295, 1, 0, 0.5,6.9149e-07)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485716,0.00247526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465808,-0.00632798) , 
8, 2.96053, 1, 0, 0.476894,-0.00556607) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718213,0.0227773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521045,-0.00102037) , 
12, 0.665608, 1, 0, 0.572999,0.0175892) , 
8, 3.56332, 1, 0, 0.5,1.05008e-06)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502293,0.000361396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383315,-0.0136018) , 
7, 5.40825, 1, 0, 0.492664,-0.00272868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590392,0.0087162) , 
7, 5.75166, 1, 0, 0.5,2.91928e-06)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670939,0.00839154) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473168,-0.00176164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543543,0.0119305) , 
10, 3.20132, 1, 0, 0.478065,-0.00332023) , 
4, 0.020289, 1, 0, 0.5,2.44485e-06)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319466,-0.00936982) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573585,0.00277886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366434,-0.00397469) , 
4, 0.207635, 1, 0, 0.512206,0.00240935) , 
6, 2.59495, 1, 0, 0.5,2.58825e-06)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492873,-0.000667657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664696,0.011363) , 
8, 3.81338, 1, 0, 0.511817,0.00223358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290401,-0.0109313) , 
6, 3.71998, 1, 0, 0.5,1.67445e-06)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498771,-0.00116228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506021,0.0186586) , 
9, 3.62923, 1, 0, 0.499472,0.00291326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505657,-0.00826939) , 
1, 0.749114, 1, 0, 0.5,1.75014e-06)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541529,-0.00172783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571888,0.00783987) , 
12, 1.29454, 1, 0, 0.551163,0.00545418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37464,0.00191909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27233,-0.0169925) , 
2, 0.0540501, 1, 0, 0.340113,-0.0170434) , 
12, 2.28249, 1, 0, 0.5,3.08982e-07)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505351,-0.000260761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706745,0.0156175) , 
1, 0.758119, 1, 0, 0.516947,0.0023897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238779,-0.0102216) , 
12, 3.57447, 1, 0, 0.5,-1.59121e-06)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498771,-0.00102117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506021,0.017417) , 
9, 3.62923, 1, 0, 0.499472,0.002934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505657,-0.00838033) , 
1, 0.749114, 1, 0, 0.5,-1.2621e-06)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460852,-0.00556908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526239,0.0051997) , 
0, 0.601338, 1, 0, 0.503586,0.00558454) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436818,-0.0117773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567749,0.00769034) , 
1, 0.494959, 1, 0, 0.490071,-0.0154721) , 
6, 3.25121, 1, 0, 0.5,-2.17984e-06)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489647,-0.00068484) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72949,0.0215462) , 
8, 3.80948, 1, 0, 0.505792,0.00269069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432485,-0.00872953) , 
8, 4.09469, 1, 0, 0.5,-2.27078e-06)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505351,-0.000245334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706745,0.0150576) , 
1, 0.758119, 1, 0, 0.516947,0.0023161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238779,-0.0099179) , 
12, 3.57447, 1, 0, 0.5,-2.45174e-09)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492128,-0.00175502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530644,0.0115292) , 
9, 3.04718, 1, 0, 0.499472,0.00284533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505657,-0.00817272) , 
1, 0.749114, 1, 0, 0.5,1.53093e-07)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314619,-0.00850431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595881,0.00338488) , 
10, 0.65201, 1, 0, 0.551163,0.00530182) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37464,0.00163684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27233,-0.0161903) , 
2, 0.0540501, 1, 0, 0.340113,-0.016569) , 
12, 2.28249, 1, 0, 0.5,-1.03413e-07)    );
   return;
};

// Clean up
inline void ReadVBFgamma::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadVBFgamma::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
